# Generated by Django 3.0.8 on 2020-07-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ofile', models.FileField(upload_to='file/output')),
                ('markfile', models.FileField(upload_to='file/markedfile')),
            ],
        ),
        migrations.CreateModel(
            name='userInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first',models.CharField(max_length=30)),
                ('second',models.CharField(max_length=30)),
                ('ifile', models.FileField(upload_to='file/input')),
            ],
        ),
    ]
